-- MySQL Script generated by MySQL Workbench
-- Thu Jun 14 21:57:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kasa_fiskalna
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kasa_fiskalna
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kasa_fiskalna` DEFAULT CHARACTER SET utf8 ;
USE `kasa_fiskalna` ;

-- -----------------------------------------------------
-- Table `kasa_fiskalna`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kasa_fiskalna`.`products` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `product_cost` DOUBLE NULL,
  `product_barcode` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`id_product`),
  UNIQUE INDEX `id_product_UNIQUE` (`id_product` ASC),
  UNIQUE INDEX `product_barcode_UNIQUE` (`product_barcode` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `kasa_fiskalna`.`products`
-- -----------------------------------------------------
START TRANSACTION;
USE `kasa_fiskalna`;
INSERT INTO `kasa_fiskalna`.`products` (`id_product`, `product_name`, `product_cost`, `product_barcode`) VALUES (1, 'dlugopis', 0,80, '4239');
INSERT INTO `kasa_fiskalna`.`products` (`id_product`, `product_name`, `product_cost`, `product_barcode`) VALUES (2, 'olowek', 1,00, '7801');
INSERT INTO `kasa_fiskalna`.`products` (`id_product`, `product_name`, `product_cost`, `product_barcode`) VALUES (3, 'blok_tech', 1,80, '3897');
INSERT INTO `kasa_fiskalna`.`products` (`id_product`, `product_name`, `product_cost`, `product_barcode`) VALUES (4, 'blok_rys', 1,20, '0123');
INSERT INTO `kasa_fiskalna`.`products` (`id_product`, `product_name`, `product_cost`, `product_barcode`) VALUES (5, 'linijka', 0,75, '3965');
INSERT INTO `kasa_fiskalna`.`products` (`id_product`, `product_name`, `product_cost`, `product_barcode`) VALUES (6, 'marker', 2,00, '1456');

COMMIT;

